### ISSUE TITLE
好项目！作者可以加一下Liscense吗

### ISSUE THREAD

**Issue by AntikaSmith** [hetu-script/random_chinese_fantasy_names#1]
试用了下感觉很不错，想用一下。但是看到又没有License说明，害怕😨

**Comment by hythl0day** [comment]
我加个MIT协议吧。
这个JS版本的是纯粹为了分享发出来的。
我自己用的是其他语言写的，所以这个JS版本的可能不是最新版。

**Comment by hythl0day** [comment]
我看了下是有协议的，你点进去NPM包的目录，就是https://github.com/hetu-script/random_chinese_fantasy_names/tree/main/www/random_names

这里放了MIT协议。

根目录是个网站，是纯展示用的，随便写的，也用不着协议吧。

不过我还是补了下。

**Comment by AntikaSmith** [comment]
> 我看了下是有协议的，你点进去NPM包的目录，就是https://github.com/hetu-script/random_chinese_fantasy_names/tree/main/www/random_names
> 
> 这里放了MIT协议。
> 
> 根目录是个网站，是纯展示用的，随便写的，也用不着协议吧。
> 
> 不过我还是补了下。

嗯嗯，看到了。谢谢作者大大~
